image: python:3.9-slim

stages:
  - test
  - lint

before_script:
  - python -V
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - python -m pytest test_calculator.py -v
  tags:
    - docker

lint:
  stage: lint
  script:
    - flake8 calculator.py test_calculator.py --max-line-length=100
    - black --check calculator.py test_calculator.py
  tags:
    - docker
