image: python:3.9-slim

stages:
  - format
  - lint
  - test

before_script:
  - python -V
  - pip install -r requirements.txt
  - pip install autopep8 black flake8

format:
  stage: format
  script:
    - autopep8 --in-place --aggressive --aggressive calculator.py test_calculator.py
    - black calculator.py test_calculator.py
    - |
      if [[ -n $(git diff) ]]; then
        git config --global user.email "gitlab@example.com"
        git config --global user.name "GitLab CI"
        git add .
        git commit -m "Apply automatic formatting with autopep8 and black"
        git push origin HEAD:$CI_COMMIT_REF_NAME
      fi
  tags:
    - docker

lint:
  stage: lint
  script:
    - flake8 calculator.py test_calculator.py --max-line-length=100
  tags:
    - docker

test:
  stage: test
  script:
    - python -m pytest test_calculator.py -v
  tags:
    - docker
